---
- name: Clean up
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Delete AWS IAM user
      community.aws.iam:
        iam_type: user
        name: "{{ item.awsiam_user }}"
        state: absent
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        index_var: index

    # Mandatory configuration for Molecule to function.
    - name: Populate instance config
      ansible.builtin.set_fact:
        instance_conf: {}

    - name: Dump instance config
      ansible.builtin.copy:
        content: "{{ instance_conf | to_json | from_json | community.molecule.to_yaml }}"
        dest: "{{ molecule_instance_config }}"
